name: coral_tester
description: A Very Good Project created by Very Good CLI.
version: 1.0.0+1
publish_to: none

environment:
  sdk: '>=2.17.0 <3.0.0'

dependencies:
  bloc: ^8.1.0
  coral_analytics_repository:
    path: ../coral_analytics_repository
  coral_bootstrap:
    path: ../coral_bootstrap
  coral_logger:
    path: ../coral_logger
  flutter_test:
    sdk: flutter
  golden_toolkit: ^0.13.0
  lumberdash: ^3.0.0
  mocktail: ^0.3.0
  print_lumberdash: ^3.0.0

dev_dependencies:
  very_good_analysis: ^3.0.1
