environment_config:
  path: environment_config.dart
  class: EnvironmentConfig

  fields:
    segment_api_write_key:
      type: String?
      env_var: 'segment_api_write_key'
    sentry_dsn:
      type: String?
      env_var: 'sentry_dsn'
