site_name: Coral Flutter

theme:
  name: readthedocs

extra_css:
  - css/extra.css

site_dir: docs_site

use_directory_urls: false

nav:
  - 'index.md'
  - 'developer_set_up.md'
  - 'architecture_overview.md'
  - 'coral_packages.md'
  - 'example_applications.md'
  - 'file_structure.md'
  - 'naming_conventions.md'
  - 'bloc_patterns.md'
  - 'application_testing.md'
  - 'error_monitoring.md'
  - 'why_flutter_bloc.md'
