name: coral_analytics_repository
version: 1.0.0+1
publish_to: none

environment:
  sdk: '>=2.17.0 <3.0.0'

dependencies:
  auto_route: ^5.0.4
  flutter:
    sdk: flutter
  flutter_segment: ^3.7.0

dev_dependencies:
  very_good_analysis: ^3.0.1
