name: coral_logger
version: 1.0.0+1
publish_to: none

environment:
  sdk: ">=2.17.0 <3.0.0"

dependencies:
  lumberdash: ^3.0.0
  print_lumberdash: ^3.0.0
  sentry: ^6.6.3
  sentry_lumberdash: ^3.2.0

dev_dependencies:
  very_good_analysis: ^3.0.1
