include: package:very_good_analysis/analysis_options.3.0.1.yaml
linter:
  rules:
    public_member_api_docs: false
    use_colored_box: false
    camel_case_types: false
    use_setters_to_change_properties: false
