name: coral_bloc
version: 1.0.0+1
publish_to: none

environment:
  sdk: '>=2.17.0 <3.0.0'

dependencies:
  bloc: ^8.1.0
  coral_logger:
    path: ../coral_logger

dev_dependencies:
  very_good_analysis: ^3.0.1
