name: counter_example

on:
  push:
    paths:
      - 'examples/counter_example/**'
      - '.github/workflows/counter_example.yaml'

jobs:
  build:
    runs-on: ubuntu-latest
    env:
      working-directory: ./examples/counter_example

    timeout-minutes: 25

    steps:
      - uses: actions/checkout@v3

      - name: Install Flutter
        uses: subosito/flutter-action@v2
        with:
          flutter-version: 3.3.4
          channel: 'stable'

      - name: Install Dependencies
        run: flutter pub get
        working-directory: ${{env.working-directory}}

      - name: Format
        run: flutter format --set-exit-if-changed lib test
        working-directory: ${{env.working-directory}}

      - name: Analyze
        run: flutter analyze lib test
        working-directory: ${{env.working-directory}}

      - name: Run tests
        run: flutter test --no-pub --coverage --test-randomize-ordering-seed random
        working-directory: ${{env.working-directory}}

      - name: Check Code Coverage
        uses: VeryGoodOpenSource/very_good_coverage@v1.1.1
        with:
          exclude: '**/*.g.dart **/bloc_type.dart **/redux_remote_devtools.dart'
          min_coverage: 100
        working-directory: ${{env.working-directory}}
