name: counter_example

on:
  push:
    paths:
      - 'examples/counter_example/**'
      - '.github/workflows/counter_example.yaml'

jobs:
  build:
    uses: VeryGoodOpenSource/very_good_workflows/.github/workflows/flutter_package.yml@v1
    with:
      flutter_channel: stable
      flutter_version: 3.3.4
      working_directory: './examples/counter_example'
      test_recursion: true
      coverage_excludes: '**/*.g.dart **/bloc_type.dart **/redux_remote_devtools.dart'
      min_coverage: 100
